### ISSUE TITLE
issue with heif-convert

### ISSUE THREAD

**Issue by ng2303** [boi4/dynwalls#3]
I'm new to ubuntu and using terminal and stuff and I'm having issues running the command python3 dynwalls use mojave.heic (i named my file mojave.heic if you're wondering). I get the error:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "dynwalls/__main__.py", line 152, in <module>
    main()
  File "dynwalls/__main__.py", line 148, in main
    dw.act(arguments.action, arguments)
  File "dynwalls/__main__.py", line 31, in act
    getattr(self, actionname)(args)
  File "dynwalls/__main__.py", line 76, in use
    heic.extract_images(arguments.heicfile,
  File "dynwalls/heic.py", line 31, in extract_images
    subprocess.run(args)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'heif-convert'

even though I've installed libheif like 60 million times. What should I do. Do I have to manually clone something else instead like something with only heif-convert? Also, how do I call to the file in the command where I select a .heif since i dont think im even doing that right haha. Pls help me I am a noob (I'm running PopOS which is based on Ubuntu by the way)

**Comment by boi4** [comment]
Hi @ng2303,
can you try installing `libheif-examples` via `sudo apt install libheif-examples`?
Basically, the traceback says that your operating system cannot locate the executable `heif-convert`. I just checked [here](https://packages.ubuntu.com/bionic/libheif-examples) and it seems like the program is part of the `libheif-examples` package (I should probably add that to the readme).

About your second question: I think the best thing to do is to open a terminal, use `cd` to change the working directory to the cloned `dynwalls` repo and run `python dynwalls` just to check that you are at the right location.
Next, you have to specify the **path** to the heif file, in your case `mojave.heic`. So if mojave.heic is in your download folder, use something like this: `dynwalls use ~/Downloads/mojave.heic` (the `~` is automatically replaced with `/home/<your username>/`).

I hope that will work for you^^

**Comment by ng2303** [comment]
thank you so much! I think the examples thing worked, but now I'm getting a new error - 
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "dynwalls/__main__.py", line 152, in <module>
    main()
  File "dynwalls/__main__.py", line 148, in main
    dw.act(arguments.action, arguments)
  File "dynwalls/__main__.py", line 31, in act
    getattr(self, actionname)(args)
  File "dynwalls/__main__.py", line 87, in use
    self.update({})
  File "dynwalls/__main__.py", line 138, in update
    subprocess.run(args)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'feh'

i ran that command with feh and it said it successfully updated as well. What should I do from here?

**Comment by ng2303** [comment]
feh issues are being references online to relate with numpy so I updated that as well

**Comment by boi4** [comment]
Can you tell me the output of the following commands:
`which feh`
`systemctl --user show-environment`

**Comment by ng2303** [comment]
I just updated feh using sudo apt install feh --upgrade and I'm not getting errors anymore!
I used python3 dynwalls enable after and timer was set
now what do I have to do

**Comment by ng2303** [comment]
after doing the enable command the background didn't change so idk what I have to change since I assumed that the enable command would just change it haha
thank you again for all of the help so far!!

**Comment by boi4** [comment]
Can you do `python3 dynwalls update`? Enable should already change it, it's probably a problem with the PATH.

**Comment by ng2303** [comment]
i did python3 dynwalls update and then ran python3 dynwalls enable and it did not work :( 
anything else that you think might help? It might have something to do with PopOS, iirc you did not run it on a ubuntu based distro so it might not work with those ig

**Comment by ng2303** [comment]
I did the set of 3 commands a few times and the symlink is being created but the background is not popping up, after i run enable it says: 

Created symlink /home/ng2303/.config/systemd/user/timers.target.wants/dynwalls.timer → /home/ng2303/.local/share/systemd/user/dynwalls.timer.

after I run enable it says
File contains 4 images
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-1.jpg
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-2.jpg
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-3.jpg
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-4.jpg

**Comment by ng2303** [comment]
i don't seem to have that .local folder nor any of the wallpaper jpg's saved anywhere on my computer hmm

**Comment by boi4** [comment]
Folders starting with a dot are hidden in your file browser, you can run `ls -la /home/ng2303` (the `a` means all) to show all files in your home directory, .local should defintely be there :)

Can you run `journalctl --user -u dynwalls` and tell me the output? It has probably something to do with the systemd service (which you can imagine being a program being run automatically by your OS) having some problem.

**Comment by ng2303** [comment]
I'm just copying everything and sending so I don't miss everything. Here - 

ng2303@pop-os:~$ cd git_environment
ng2303@pop-os:~/git_environment$ cd dynwalls
ng2303@pop-os:~/git_environment/dynwalls$ journalctl --user -u dynwalls
-- Logs begin at Wed 2020-07-15 23:44:21 CDT, end at Thu 2020-10-01 14:09:18 CD>
Oct 01 12:00:32 pop-os systemd[1411]: Started Update Dynamic Wallpaper.
Oct 01 12:00:33 pop-os systemd[1411]: dynwalls.service: Succeeded.
lines 1-3/3 (END)...skipping...
-- Logs begin at Wed 2020-07-15 23:44:21 CDT, end at Thu 2020-10-01 14:09:18 CDT. --
Oct 01 12:00:32 pop-os systemd[1411]: Started Update Dynamic Wallpaper.
Oct 01 12:00:33 pop-os systemd[1411]: dynwalls.service: Succeeded.
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-3/3 (END)


















































-- Logs begin at Wed 2020-07-15 23:44:21 CDT, end at Thu 2020-10-01 14:09:18 CDT. --
Oct 01 12:00:32 pop-os systemd[1411]: Started Update Dynamic Wallpaper.
Oct 01 12:00:33 pop-os systemd[1411]: dynwalls.service: Succeeded.
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-3/3 (END)

**Comment by boi4** [comment]
Ok, everything seems fine, can you send the output `cat ~/.local/share/dynwalls/config.json` (which is the main config file for dynwalls)?

**Comment by ng2303** [comment]
{"wp_cmd": "feh --bg-fill --no-fehbg {}", "dyn_config": {"ti": [{"t": 0.0, "i": 1}, {"t": 0.25, "i": 0}, {"t": 0.5, "i": 2}, {"t": 0.75, "i": 3}], "ap": {"d": 1, "l": 0}}}

**Comment by boi4** [comment]
Ok, can you try one more thing:
`feh --bg-fill --no-fehbg ~/.local/share/dynwalls/images/wallpaper-1.jpg`
If that doesn't change your wallpaper then I am really confused :D

**Comment by ng2303** [comment]
didn't do it :( is that command supposed to have a message after it or anything because it just finishes and gives me a clear terminal line to write something

**Comment by ng2303** [comment]
do you need to set up feh in any way for it to work ?

**Comment by boi4** [comment]
If you are using PopOS and are not that familiar with the command line, I can assume that you run the default desktop environment of PopOS (Gnome) (does your desktop look similar to this: https://linuxhint.com/wp-content/uploads/2019/12/2-40.png)?

If yes, I think you cannot use feh to change your background, but can use the following (I googled it quickly):
`gsettings get org.gnome.desktop.background picture-uri 'file:///home/ng2303/.local/share/dynwalls/images/wallpaper-1.jpg'`

If that works, you should run `python3 dynwalls usecmd "gsettings get org.gnome.desktop.background picture-uri file://{}"`, I think. Then everything else should work hopefully.

**Comment by ng2303** [comment]
yeah lol i forgot to mention i'm pretty sure i'm running gnome

**Comment by ng2303** [comment]
i used the first thing you sent and got this back

'file:///home/ng2303/.local/share/dynwalls/images/wallpaper-1.jpg'
Usage:
  gsettings [--schemadir SCHEMADIR] get SCHEMA[:PATH] KEY

Get the value of KEY

Arguments:
  SCHEMADIR A directory to search for additional schemas
  SCHEMA    The name of the schema
  PATH      The path, for relocatable schemas
  KEY       The key within the schema

**Comment by boi4** [comment]
Oh you should probably use `set` and not `get`, sorry :D

**Comment by boi4** [comment]
I looked at this guide: https://linuxconfig.org/set-wallpaper-on-ubuntu-20-04-using-command-line 
Step 3 should be the one

**Comment by ng2303** [comment]
the command worked with set (first one)
will try second

**Comment by ng2303** [comment]
when i ran second one it said it wasn't a correct action, should it be setcmd or use maybe?

**Comment by boi4** [comment]
Yes, it should be setcmd, my bad.

**Comment by ng2303** [comment]
it said successfully updated wallpaper command! how should I check if it'll change with time?

**Comment by ng2303** [comment]
thank you so much btw! I find it crazy that this issue got so much attention in a repo with one or 2 devs vs howdy with much more not getting any attention haha

**Comment by boi4** [comment]
No worries^^ Your issue is the second issue ever. To test if it will change with time, you can either 
a) wait (it's 6 hours each picture in your case) or
b) use the `gsettings get org.gnome.desktop.background picture-uri 'file://'` with some random picture (this will overwrite the current background) and then run `systemctl --user start dynwalls` which will simulate the triggering of a new wallpaper by time. If the wallpaper changes after that command everything should work fine.

**Comment by ng2303** [comment]
I think i'll just wait I have a test i desperately need to study for haha. I'll close this later today if all seems well with the transitions! Thank you so much again!

**Comment by boi4** [comment]
Perfect :ok_hand:

**Comment by ng2303** [comment]
um it does not appear to have changed over the last 9 hours...... what now?

**Comment by boi4** [comment]
What does `journalctl --user -u dynwalls` say?

**Comment by ng2303** [comment]
-- Logs begin at Wed 2020-07-15 23:44:21 CDT, end at Fri 2020-10-02 01:19:26 CDT. --
-- No entries --

 odd, since I had only cloned and set up the repo in the last few days.......

**Comment by boi4** [comment]
Can you do `systemctl --user start dynwalls` and look whether the wallpaper changes?
And can you also send the output of `systemctl --user cat dynwalls.timer` this should list the time when the wallpaper changes

**Comment by ng2303** [comment]
first command did not change background
here are times: 
[Unit]
Description=Update Wallpaper at specific times

[Timer]
OnCalendar=*-*-* 00:00:00
OnCalendar=*-*-* 03:00:00
OnCalendar=*-*-* 06:00:00
OnCalendar=*-*-* 09:00:00
OnCalendar=*-*-* 12:00:00
OnCalendar=*-*-* 15:00:00
OnCalendar=*-*-* 18:00:00
OnCalendar=*-*-* 21:00:00
Persistent=true

**Comment by boi4** [comment]
These are the times when the wallpaper should change...
Are you sure you ran `python3 dynwalls usecmd "gsettings get org.gnome.desktop.background picture-uri file://{}"`?
What's the output of `cat ~/.local/share/dynwalls/config.json`?

Maybe the changes are very subtle and you didn't notice them :D If you want you can browse `~/.local/share/dynwalls/images` with your file manager and look at the wallpapers yourself

**Comment by ng2303** [comment]
well i went back into windows and just tried to run pop-os again (I run dual boot) and it's freezing up so it's gonna be a while before I get it fixed again so......

**Comment by ng2303** [comment]
it's remained light all day lol it turns from day to night there's no way I missed it. the cat command sends this, it seems correct:

{"wp_cmd": "gsettings get org.gnome.desktop.background picture-uri file://{}", "dyn_config": {"ti": [{"t": 0.0, "i": 0}, {"t": 0.125, "i": 1}, {"t": 0.25, "i": 2}, {"t": 0.375, "i": 3}, {"t": 0.5, "i": 4}, {"t": 0.625, "i": 5}, {"t": 0.75, "i": 6}, {"t": 0.875, "i": 7}], "ap": {"d": 7, "l": 0}}}

how do I browse the hidden folders such as .local?

**Comment by boi4** [comment]
try `xdg-open ~/.local`

or search for something like `show hidden files` in the options

**Comment by ng2303** [comment]
yeah used xdg command all the pictures seem to have made the transition from .heif to jpeg well, none are glitched or anything

**Comment by boi4** [comment]
Ok, then I think it may be a problem with the environment variables not being exposed...
You could try running `git checkout 344a1e46deaeda00410912b09ee8c5ae857acaec` in the dynwalls folder and then run the setcmd and enable command again. Maybe it will work then

**Comment by ng2303** [comment]
ok i did that will update you if I see any changes

**Comment by ng2303** [comment]
it's still not changing but I ran a command you said to check if time changes (
systemctl --user start dywnalls) and this is the output:
Failed to start dywnalls.service: Unit dywnalls.service not found.

i cd'd into dywnalls as well btw

**Comment by boi4** [comment]
Did you do setcmd, use and enable?
The `use` command should create the dynwalls service

**Comment by ng2303** [comment]
i did a new cycle of the setcmd use and enable and when I use enable i get this:

Usage:
  gsettings [--schemadir SCHEMADIR] get SCHEMA[:PATH] KEY

Get the value of KEY

Arguments:
  SCHEMADIR A directory to search for additional schemas
  SCHEMA    The name of the schema
  PATH      The path, for relocatable schemas
  KEY       The key within the schema

when I use the use command, there is this error at the end:

FileExistsError: [Errno 17] File exists: '/home/ng2303/.local/share/dynwalls/dynwalls.timer' -> '/home/ng2303/.local/share/systemd/user//dynwalls.timer'

**Comment by ng2303** [comment]
I'm also getting the same failed to start service error when I use systemctl --user start dywnalls

**Comment by boi4** [comment]
Ahhhh, I finally found the error :D  
I wrote `gsettings get` instead of `gsettings set`
The correct command should be:
`python3 dynwalls usecmd "gsettings set org.gnome.desktop.background picture-uri file://{}"`

Can you run that, then use, then enable?

**Comment by ng2303** [comment]
do you mean python3 dynwalls setcmd "gsettings set org.gnome.desktop.background picture-uri file://{}"

i think you meant setcmd rather than usecmd

**Comment by ng2303** [comment]
still got the same effect when using the updated command for gsettings, still shows me a usage message

**Comment by ng2303** [comment]
and im still getting the service not found

**Comment by ng2303** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "dynwalls/__main__.py", line 153, in <module>
    main()
  File "dynwalls/__main__.py", line 149, in main
    dw.act(arguments.action, arguments)
  File "dynwalls/__main__.py", line 32, in act
    getattr(self, actionname)(args)
  File "dynwalls/__main__.py", line 86, in use
    systemd.setup_units(timelist)
  File "dynwalls/systemd.py", line 103, in setup_units
    _install_files(timerfile=timerfile
  File "dynwalls/systemd.py", line 76, in _install_files
    lnabs(timerfile,unitdir)
  File "dynwalls/systemd.py", line 72, in lnabs
    os.symlink(src,dst)
FileExistsError: [Errno 17] File exists: '/home/ng2303/.local/share/dynwalls/dynwalls.timer' -> '/home/ng2303/.local/share/systemd/user//dynwalls.timer'

**Comment by boi4** [comment]
Yes it should have been setcmd. Okay run this:
```
systemctl --user disable dynwalls.timer
rm ~/.local/share/systemd/user/dynwalls.timer
rm ~/.local/share/systemd/user/dynwalls.service
rm -r ~/.local/share/dynwalls
systemctl --user daemon-reload

# in the dynwalls directory
git checkout master
python3 dynwalls setcmd "gsettings set org.gnome.desktop.background picture-uri file://{}"
python3 dynwalls use PATH_TO_HEIC
python3 dynwalls enable
```
Try to understand what these commands do before you use them.

Sorry for all the hassle, I think I will maybe run popos on a vm for testing and check whether this works.

**Comment by ng2303** [comment]
I'm sorry that I'm giving you a hassle haha you shouldn't be sorry. I am still getting the gsettings schemadir error, I think we might not be utilizing gsettings correctly. It also didn't reset the background.

**Comment by ng2303** [comment]
ng2303@pop-os:~$ systemctl --user disable dynwalls.timer
Removed /home/ng2303/.config/systemd/user/timers.target.wants/dynwalls.timer.
ng2303@pop-os:~$ rm ~/.local/share/systemd/user/dynwalls.timer
ng2303@pop-os:~$ rm ~/.local/share/systemd/user/dynwalls.service
ng2303@pop-os:~$ rm -r ~/.local/share/dynwalls
ng2303@pop-os:~$ systemctl --user daemon-reload
ng2303@pop-os:~$ cd git_environment
ng2303@pop-os:~/git_environment$ cd dynwalls
ng2303@pop-os:~/git_environment/dynwalls$ git checkout master
Previous HEAD position was 344a1e4 Fix off by one error when loading images
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
ng2303@pop-os:~/git_environment/dynwalls$ python3 dynwalls setcmd "gsettings set org.gnome.desktop.background picture-uri file://{}"
No Config specified so far
Successfully updated wallpaper command.
ng2303@pop-os:~/git_environment/dynwalls$ python3 dynwalls use /home/ng2303/Downloads/5k.heic
File contains 8 images
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-1.jpg
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-2.jpg
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-3.jpg
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-4.jpg
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-5.jpg
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-6.jpg
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-7.jpg
Written to /home/ng2303/.local/share/dynwalls/images/wallpaper-8.jpg
Usage:
  gsettings [--schemadir SCHEMADIR] set SCHEMA[:PATH] KEY VALUE

Set the value of KEY to VALUE

Arguments:
  SCHEMADIR A directory to search for additional schemas
  SCHEMA    The name of the schema
  PATH      The path, for relocatable schemas
  KEY       The key within the schema
  VALUE     The value to set


ng2303@pop-os:~/git_environment/dynwalls$ python3 dynwalls enable
Created symlink /home/ng2303/.config/systemd/user/timers.target.wants/dynwalls.timer → /home/ng2303/.local/share/systemd/user/dynwalls.timer.
Usage:
  gsettings [--schemadir SCHEMADIR] set SCHEMA[:PATH] KEY VALUE

Set the value of KEY to VALUE

Arguments:
  SCHEMADIR A directory to search for additional schemas
  SCHEMA    The name of the schema
  PATH      The path, for relocatable schemas
  KEY       The key within the schema
  VALUE     The value to set

**Comment by ng2303** [comment]
just sent everything in terminal in case you see me doing anything wrong haha

**Comment by flohw** [comment]
Hi @ng2303 

Try this:

`python3 dynwalls setcmd 'gsettings set org.gnome.desktop.background picture-uri "file://{}"` then `python3 dynwalls update`

Please, for readability use three backquotes ` then a break line, paste your long text, a break line then three backquotes again.

    ```
    Pasted code
    ```

If you want to `inline a command` use only a single backquote around the words you want.
Use the `Preview` tab above the editor to make sure everything is ok.

On a fr keyboard you type `AltGr`+`7`. I let you find yours :wink: 

Thank you for our eyes and our brains :grin:

**Comment by boi4** [comment]
The problem is that `dynwalls` will try to split the 'setcmd' like the shell usually does and then replaces a single `{}` with the image. This will not work here because the actual token is `file://{}` instead. I will fix this.

**Comment by boi4** [comment]
@ng2303, please open a shell in the `dynwalls` directory and run `git pull` to get the latest version of dynwalls.

Then try running the commands that @flohw stated in his comment. Hopefully, it's fixed now.

**Comment by ng2303** [comment]
I updated, ran @flohw commands, and set it to use a heic. before clicking enable, it already changed the background, and it seems that it fits the time - I think it is finally working! Will give updates tomorrow but I think we are actually good this time.

**Comment by boi4** [comment]
Awesome!

**Comment by ng2303** [comment]
yup just woke up and everything seems to be working! closing the thread rn thanks for all the help @boi4 and @flohw!
