### ISSUE TITLE
Unknown file 

### ISSUE THREAD

**Issue by michael-pisman** [boi4/dynwalls#5]
Hi, really interested in your project. However I got some problems, maybe you could help me. 

I created `.heic` with [this website](https://dynamicwallpaper.club), used jpg images, and timestamps instead of sun position. 

I tried to install all the required libraries, and I think it went well.
I use **Debian Buster 10**(Raspbian buster to be precise) on RPI4. 
**X** for display manager, **i3wm** for the window manager. Have wallpaper set with feh.

This is what I do:

```
❯ python3 dynwalls setcmd 'feh --bg-fill --no-fehbg {}'
Successfully updated wallpaper command.
```

```
❯ python3 dynwalls use ../dwallpaper.heic
Unknown file type in /home/mpisman/.local/share/dynwalls/images/wallpaper.jpg
feh WARNING: /home/mpisman/.local/share/dynwalls/images/wallpaper-1.jpg does not exist - skipping
feh: No loadable images specified.
See 'man feh' for detailed usage information
```

Well, hope to use your tool, since that is exactly what I was looking for.

**Comment by flohw** [comment]
Hello @mike-pisman,

I use the same website for the heic files and have no problem. I download from the gallery instead of creating mine. Can you try with [this one](https://dynamicwallpaper.club/wallpaper/qvvk60oi7v] which work for me (on archlinux).

Maybe you can provide your custom file to try on our side?

Thank you

**Comment by michael-pisman** [comment]
Hi, @flohw 

The issue was with `libheif`. After following [this issue](https://github.com/pi3d/pi3d_demos/issues/24#issuecomment-733824260) and reinstalling most of the packages from source(official Debian packages are old), everything worked. Thank you anyway!
